version: '3.7'

services:
  indexer:
    container_name: indexer
    build: ./indexer
    env_file:
      - .env
    command: ["python", "sync_txs.py"]
  indexer:
    container_name: indexer
    build: ./indexer
    env_file:
      - .env
    command: ["python", "add_geodata_to_txs.py"]
volumes:
  static:
