version: '3.7'

services:
  indexer:
    container_name: indexer
    build: ./indexer
    env_file:
      - .env
    command: ["python", "app-gunicorn"]
  indexer:
    container_name: indexer
    build: ./indexer
    env_file:
      - .env
    command: ["python", "app-gunicorn"]
volumes:
  static:
