version: '3.7'

services:
  # pocket:
  #   container_name: pocket
  #   cap_add:
  #   - ALL
  #   build: ./pocket/
  #   ports:
  #   - "26657:26657"
  #   - "8081:8081"
  #   - "26656:26656"
  #   volumes:
  #   - "./data/pocket/:/root/.pocket/"
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
      # - ./postgres:/docker-entrypoint-initdb.d
#  indexer:
#    container_name: indexer
#    build: ./indexer
#    env_file:
#      - .env
#    depends_on:
#      - postgres
      # - pocket

  # redis:
  #   image: redis:latest
  #   container_name: superset_cache
  #   restart: unless-stopped
  #   volumes:
  #     - redis:/data

  # superset-init:
  #   image: apache/superset:${TAG:-latest-dev}
  #   container_name: superset_init
  #   command: ["/app/docker/docker-init.sh"]
  #   env_file: data/superset/.env-pokt
  #   depends_on:
  #     - redis
  #     - postgres
  #   user: "root"
  #   volumes:
  #     - ./data/superset:/app/docker
  #     - ./data/superset_home:/app/superset_home

  # superset:
  #   env_file: data/superset/.env-pokt
  #   image: apache/superset:${TAG:-latest-dev}
  #   container_name: superset_app
  #   command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
  #   user: "root"
  #   restart: unless-stopped
  #   ports:
  #     - 8088:8088
  #   depends_on:
  #     - redis
  #     - postgres
  #   volumes:
  #     - ./data/superset:/app/docker
  #     - ./data/superset_home:/app/superset_home

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=zaq1
      - GF_USERS_DEFAULT_THEME=dark
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  # redis:
  #   external: false
  static:
