apiVersion: 1
# list of datasources that should be deleted from the database
# deleteDatasources:
#   - name: telegraf
#     orgId: 1

datasources:
  - name: postgres
    type: postgres
    url: postgres:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"
