{
 "title": "Relays by Country",
 "time": { "from": "2022-05-31T21:27:57.498Z", "to": "2022-06-02T07:15:23.409Z" },
 "templating": {
  "list": [
   {
    "name": "Country",
    "query": "SELECT DISTINCT country FROM transaction"
   }
  ]
 },
 "panels": [
  {
   "title": "Reward per Country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  country as metric,\n  sum(amount) AS \"value\"\nFROM transaction\nWHERE\n  msg_type='claim' and\n  $__timeFilter(\"timestamp\")\nGROUP BY \"timestamp\", country\nORDER BY \"timestamp\"\n"
    }
   ]
  },
  {
   "title": "Total reward from relays",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  tr.\"timestamp\" AS \"time\",\n  ch.name AS metric,\n  sum(tr.amount) AS value\nFROM transaction as tr\nLEFT JOIN chains as ch ON tr.chain=ch.chain\nWHERE\n  tr.msg_type='claim' and\n  $__timeFilter(tr.\"timestamp\")\nGROUP BY \"time\", ch.name\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Reward per chain by Country",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  tr.\"timestamp\" AS \"time\",\n  ch.name AS metric,\n  sum(tr.amount) AS value\nFROM transaction as tr\nLEFT JOIN chains as ch ON tr.chain=ch.chain\nWHERE \n  tr.country IN ($Country) and\n  $__timeFilter(tr.\"timestamp\")\nGROUP BY tr.\"timestamp\",ch.name\nORDER BY timestamp ASC, value DESC\n\n\n\n\n\n\n"
    }
   ]
  }
 ]
}