## Expose the grafana service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  enabled: true
  type: NodePort
  # port: 30180
  # targetPort: 3000
  #   # targetPort: 4181 To be used with a proxy extraContainer
  # annotations: {}
  # labels: {}
  # portName: service


# Administrator credentials when not using an existing secret (see below)
adminUser: admin
adminPassword: zaq1xsw2


## Pass the plugins you want installed as a list.
##
plugins: []
  # - digrich-bubblechart-panel
  # - grafana-clock-panel

## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
##
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: postgres
      type: postgres
      url: postgres-postgresql.postgres.svc.cluster.local:5432
      database: postgres
      user: postgres
      isDefault: true
      secureJsonData:
        password: postgres
      jsonData:
        sslmode: "disable"

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

## Configure grafana dashboard to import
## NOTE: To use dashboards you must also enable/configure dashboardProviders
## ref: https://grafana.com/dashboards
##
## dashboards per provider, use provider name as key.
##
dashboards:
  default:
    some-dashboard:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": {
                  "type": "grafana",
                  "uid": "-- Grafana --"
                },
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "target": {
                  "limit": 100,
                  "matchAny": false,
                  "tags": [],
                  "type": "dashboard"
                },
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "fiscalYearStartMonth": 0,
          "graphTooltip": 0,
          "id": 1,
          "links": [],
          "liveNow": false,
          "panels": [
            {
              "datasource": {
                "type": "postgres",
                "uid": "PA942B37CCFAF5A81"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "bars",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "normal"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "id": 4,
              "options": {
                "legend": {
                  "calcs": [
                    "mean"
                  ],
                  "displayMode": "table",
                  "placement": "right"
                },
                "tooltip": {
                  "mode": "multi",
                  "sort": "desc"
                }
              },
              "targets": [
                {
                  "datasource": {
                    "type": "postgres",
                    "uid": "PA942B37CCFAF5A81"
                  },
                  "format": "time_series",
                  "group": [
                    {
                      "params": [
                        "$__interval",
                        "none"
                      ],
                      "type": "time"
                    }
                  ],
                  "metricColumn": "none",
                  "rawQuery": true,
                  "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  country as metric,\n  sum(amount) AS \"value\"\nFROM transaction\nWHERE\n  msg_type='claim' and\n  $__timeFilter(\"timestamp\")\nGROUP BY \"timestamp\", country\nORDER BY \"timestamp\"\n",
                  "refId": "A",
                  "select": [
                    [
                      {
                        "params": [
                          "amount"
                        ],
                        "type": "column"
                      },
                      {
                        "params": [
                          "sum"
                        ],
                        "type": "aggregate"
                      },
                      {
                        "params": [
                          "value"
                        ],
                        "type": "alias"
                      }
                    ]
                  ],
                  "table": "transaction",
                  "timeColumn": "\"timestamp\"",
                  "timeColumnType": "timestamp",
                  "where": [
                    {
                      "name": "$__timeFilter",
                      "params": [],
                      "type": "macro"
                    },
                    {
                      "datatype": "varchar",
                      "name": "",
                      "params": [
                        "country",
                        "IN",
                        "$Country"
                      ],
                      "type": "expression"
                    }
                  ]
                }
              ],
              "title": "Reward per Country",
              "type": "timeseries"
            },
            {
              "datasource": {
                "type": "postgres",
                "uid": "PA942B37CCFAF5A81"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "bars",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "normal"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "none"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 12,
                "y": 0
              },
              "id": 6,
              "options": {
                "legend": {
                  "calcs": [
                    "mean"
                  ],
                  "displayMode": "table",
                  "placement": "right"
                },
                "tooltip": {
                  "mode": "multi",
                  "sort": "desc"
                }
              },
              "targets": [
                {
                  "datasource": {
                    "type": "postgres",
                    "uid": "PA942B37CCFAF5A81"
                  },
                  "format": "time_series",
                  "group": [
                    {
                      "params": [
                        "$__interval",
                        "none"
                      ],
                      "type": "time"
                    },
                    {
                      "params": [
                        "country"
                      ],
                      "type": "column"
                    }
                  ],
                  "metricColumn": "none",
                  "rawQuery": true,
                  "rawSql": "SELECT\n  tr.\"timestamp\" AS \"time\",\n  ch.name AS metric,\n  sum(tr.amount) AS value\nFROM transaction as tr\nLEFT JOIN chains as ch ON tr.chain=ch.chain\nWHERE\n  tr.msg_type='claim' and\n  $__timeFilter(tr.\"timestamp\")\nGROUP BY \"time\", ch.name\nORDER BY \"time\"",
                  "refId": "A",
                  "select": [
                    [
                      {
                        "params": [
                          "amount"
                        ],
                        "type": "column"
                      },
                      {
                        "params": [
                          "sum"
                        ],
                        "type": "aggregate"
                      },
                      {
                        "params": [
                          "amount"
                        ],
                        "type": "alias"
                      }
                    ]
                  ],
                  "table": "transaction",
                  "timeColumn": "\"timestamp\"",
                  "timeColumnType": "timestamp",
                  "where": [
                    {
                      "name": "$__timeFilter",
                      "params": [],
                      "type": "macro"
                    }
                  ]
                }
              ],
              "title": "Total reward by chains",
              "type": "timeseries"
            },
            {
              "datasource": {
                "type": "postgres",
                "uid": "PA942B37CCFAF5A81"
              },
              "fieldConfig": {
                "defaults": {
                  "color": {
                    "mode": "palette-classic"
                  },
                  "custom": {
                    "axisLabel": "",
                    "axisPlacement": "auto",
                    "barAlignment": 0,
                    "drawStyle": "bars",
                    "fillOpacity": 0,
                    "gradientMode": "none",
                    "hideFrom": {
                      "legend": false,
                      "tooltip": false,
                      "viz": false
                    },
                    "lineInterpolation": "linear",
                    "lineWidth": 1,
                    "pointSize": 5,
                    "scaleDistribution": {
                      "type": "linear"
                    },
                    "showPoints": "auto",
                    "spanNulls": false,
                    "stacking": {
                      "group": "A",
                      "mode": "normal"
                    },
                    "thresholdsStyle": {
                      "mode": "off"
                    }
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      },
                      {
                        "color": "red",
                        "value": 80
                      }
                    ]
                  },
                  "unit": "none"
                },
                "overrides": []
              },
              "gridPos": {
                "h": 17,
                "w": 24,
                "x": 0,
                "y": 8
              },
              "id": 2,
              "options": {
                "legend": {
                  "calcs": [
                    "mean"
                  ],
                  "displayMode": "table",
                  "placement": "right"
                },
                "tooltip": {
                  "mode": "multi",
                  "sort": "desc"
                }
              },
              "targets": [
                {
                  "datasource": {
                    "type": "postgres",
                    "uid": "PA942B37CCFAF5A81"
                  },
                  "format": "time_series",
                  "group": [],
                  "metricColumn": "none",
                  "rawQuery": true,
                  "rawSql": "\nSELECT\n  tr.\"timestamp\" AS \"time\",\n  ch.name AS metric,\n  sum(tr.amount) AS value\nFROM transaction as tr\nLEFT JOIN chains as ch ON tr.chain=ch.chain\nWHERE \n  tr.country IN ($Country) and\n  $__timeFilter(tr.\"timestamp\")\nGROUP BY tr.\"timestamp\",ch.name\nORDER BY timestamp ASC, value DESC\n\n\n\n\n\n\n",
                  "refId": "A",
                  "select": [
                    [
                      {
                        "params": [
                          "value"
                        ],
                        "type": "column"
                      }
                    ]
                  ],
                  "timeColumn": "time",
                  "where": [
                    {
                      "name": "$__timeFilter",
                      "params": [],
                      "type": "macro"
                    }
                  ]
                }
              ],
              "title": "Relays per chain by Country",
              "type": "timeseries"
            }
          ],
          "refresh": false,
          "schemaVersion": 36,
          "style": "dark",
          "tags": [],
          "templating": {
            "list": [
              {
                "current": {
                  "selected": true,
                  "text": [
                    "All"
                  ],
                  "value": [
                    "$__all"
                  ]
                },
                "datasource": {
                  "type": "postgres",
                  "uid": "PA942B37CCFAF5A81"
                },
                "definition": "SELECT DISTINCT country FROM transaction",
                "hide": 0,
                "includeAll": true,
                "multi": true,
                "name": "Country",
                "options": [],
                "query": "SELECT DISTINCT country FROM transaction",
                "refresh": 1,
                "regex": "",
                "skipUrlSync": false,
                "sort": 1,
                "type": "query"
              }
            ]
          },
          "time": {
            "from": "now-90d",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": [
              "1m",
              "5m",
              "15m",
              "30m",
              "1h"
            ]
          },
          "timezone": "",
          "title": "POKT relays stat",
          "uid": "YthL9WzVz",
          "version": 1,
          "weekStart": ""
        }

